# Error
ERROR_LOCATION_MISSING = "Error: invalid location name."

# Survrun times
TIME_SURVRUN_MIN_TIMEBOX = 20
TIME_SURVRUN_MAX_TIMEBOX = 60

# City names
CITY_WINDHELM = "Windhelm"
CITY_FALKREATH = "Falkreath"
CITY_SOLITUDE = "Solitude"
CITY_MORTHAL = "Morthal"
CITY_DAWNSTAR = "Dawnstar"
CITY_MARKARTH = "Markarth"
CITY_RIFTEN = "Riften"
CITY_WHITERUN = "Whiterun"
CITY_WINTERHOLD = "Winterhold"

# Locations
LOC_HIGH_HROTHGAR = "High Hrothgar"
LOC_STAUBMANSGRAB = "Staubmansgrab"
LOC_HEXENFELSENSCHANZE = "Hexenfelsenschanze"

# Complete Survrun possible target location list
LIST_SURVRUN_TARGET_LOCATIONS = locations = [
    ERROR_LOCATION_MISSING,
    CITY_WINDHELM,
    CITY_FALKREATH,
    CITY_SOLITUDE,
    CITY_MORTHAL,
    CITY_DAWNSTAR,
    CITY_MARKARTH,
    CITY_RIFTEN,
    CITY_WHITERUN,
    CITY_WINTERHOLD,
    LOC_HIGH_HROTHGAR,
    LOC_STAUBMANSGRAB,
    LOC_HEXENFELSENSCHANZE
]

# Survrun locations split in vertical sectors
LIST_SURVRUN_SECTOR_A = [
    CITY_MARKARTH,
    LOC_HEXENFELSENSCHANZE,
]

LIST_SURVRUN_SECTOR_B = [
    CITY_SOLITUDE,
    CITY_MORTHAL,
    CITY_DAWNSTAR
]

LIST_SURVRUN_SECTOR_C = [
    CITY_WHITERUN,
    CITY_FALKREATH,
    LOC_STAUBMANSGRAB,
    LOC_HIGH_HROTHGAR
]

LIST_SURVRUN_SECTOR_D = [
    CITY_WINDHELM,
    CITY_WINTERHOLD
]

LIST_SURVRUN_SECTOR_E = [
    CITY_RIFTEN
]
