# Error
ERROR_LOCATION_MISSING = "Error: invalid location name."

# Survrun times
TIME_SURVRUN_MIN_TIMEBOX = 30
TIME_SURVRUN_MAX_TIMEBOX = 70

# City names
CITY_WINDHELM = "Windhelm"
CITY_FALKREATH = "Falkreath"
CITY_SOLITUDE = "Solitude"
CITY_MORTHAL = "Morthal"
CITY_DAWNSTAR = "Dawnstar"
CITY_MARKARTH = "Markarth"
CITY_RIFTEN = "Riften"
CITY_WHITERUN = "Whiterun"
CITY_WINTERHOLD = "Winterhold"

# Village names
VILLAGE_DRAGON_BRIDGE = "Dragon Bridge"
VILLAGE_KARTHWASTEN = "Karthwasten"
VILLAGE_RORIKSTEAD = "Rorikstead"
VILLAGE_RIVERWOOD = "Riverwood"
VILLAGE_HELGEN = "Helgen"
VILLAGE_IVARSTEAD = "Ivarstead"
VILLAGE_SHORS_STONE = "Shors Stone"

# Locations
LOC_HIGH_HROTHGAR = "High Hrothgar"
LOC_STAUBMANSGRAB = "Staubmansgrab"
LOC_HEXENFELSENSCHANZE = "Hexenfelsenschanze"

# Complete Survrun possible target location list
LIST_SURVRUN_TARGET_LOCATIONS = locations = [
    ERROR_LOCATION_MISSING,
    CITY_WINDHELM,
    CITY_FALKREATH,
    CITY_SOLITUDE,
    CITY_MORTHAL,
    CITY_DAWNSTAR,
    CITY_MARKARTH,
    CITY_RIFTEN,
    CITY_WHITERUN,
    CITY_WINTERHOLD,
    VILLAGE_DRAGON_BRIDGE,
    VILLAGE_KARTHWASTEN,
    VILLAGE_RORIKSTEAD,
    VILLAGE_RIVERWOOD,
    VILLAGE_HELGEN,
    VILLAGE_IVARSTEAD,
    VILLAGE_SHORS_STONE,
    LOC_HIGH_HROTHGAR,
    LOC_STAUBMANSGRAB,
    LOC_HEXENFELSENSCHANZE
]

# Survrun locations split in vertical sectors
LIST_SURVRUN_SECTOR_A = [
    CITY_MARKARTH,
    VILLAGE_KARTHWASTEN,
    LOC_HEXENFELSENSCHANZE
]

LIST_SURVRUN_SECTOR_B = [
    CITY_SOLITUDE,
    CITY_MORTHAL,
    CITY_DAWNSTAR,
    VILLAGE_DRAGON_BRIDGE
]

LIST_SURVRUN_SECTOR_C = [
    CITY_WHITERUN,
    CITY_FALKREATH,
    VILLAGE_RORIKSTEAD,
    VILLAGE_RIVERWOOD,
    VILLAGE_HELGEN,
    VILLAGE_IVARSTEAD,
    LOC_STAUBMANSGRAB,
    LOC_HIGH_HROTHGAR
]

LIST_SURVRUN_SECTOR_D = [
    CITY_WINDHELM,
    CITY_WINTERHOLD
]

LIST_SURVRUN_SECTOR_E = [
    CITY_RIFTEN,
    VILLAGE_SHORS_STONE
]
