MODE_NAME = "Elder Scrolls Online"

# classes
CLASS_DRAGONKNIGHT = "Dragonknight"
CLASS_SORCERER = "Sorcerer"
CLASS_NIGHTBLADE = "Nightblade"
CLASS_TEMPLAR = "Templar"
CLASS_WARDEN = "Warden"
CLASS_NECRO = "Necromancer"

# full class list
LIST_ESO_CLASSES = [
    CLASS_DRAGONKNIGHT,
    CLASS_SORCERER,
    CLASS_NIGHTBLADE,
    CLASS_TEMPLAR,
    CLASS_WARDEN,
    CLASS_NECRO
]

# 4-man instance dungeons (Base game, No DLC)
DUNGEON_ARX_CORINIUM = "Arx Corinium"
DUNGEON_BANISHED_CELLS_I = "Banished Cells I"
DUNGEON_BANISHED_CELLS_II = "Banished Cells II"
DUNGEON_BLACKHEART_HAVEN = "Blackheart Haven"
DUNGEON_BLESSED_CRUCIBLE = "Blessed Crucible"
DUNGEON_CITY_OF_ASH_I = "City of Ash I"
DUNGEON_CITY_OF_ASH_II = "City of Ash II"
DUNGEON_CRYPT_OF_HEARTS_I = "Crypt of Hearts I"
DUNGEON_CRYPT_OF_HEARTS_II = "Crypt of Hearts II"
DUNGEON_DARKSHADE_CAVERNS_I = "Darkshade Caverns I"
DUNGEON_DARKSHADE_CAVERNS_II = "Darkshade Caverns II"
DUNGEON_DIREFROST_KEEP = "Direfrost Keep"
DUNGEON_FUNGAL_GROTTO_I = "Fungal Grotto I"
DUNGEON_FUNGAL_GROTTO_II = "Fungal Grotto II"
DUNGEON_ELDEN_HOLLOW_I = "Elden Hollow I"
DUNGEON_ELDEN_HOLLOW_II = "Elden Hollow II"
DUNGEON_SELENES_WEB = "Selene's Web"
DUNGEON_SPINDLECLUTCH_I = "Spindleclutch I"
DUNGEON_SPINDLECLUTCH_II = "Spindleclutch II"
DUNGEON_TEMPEST_ISLAND = "Tempest Island"
DUNGEON_VAULTS_OF_MADNESS = "Vaults of Madness"
DUNGEON_VOLENFELL = "Volenfell"
DUNGEON_WAYREST_SEWERS_I = "Wayrest Sewers I"
DUNGEON_WAYREST_SEWERS_II = "Wayrest Sewers II"

# 4-man instance dungeons (Dragon Bones DLC)
DUNGEON_FENG_LAIR = "Feng Lair"
DUNGEON_SCALECALLER_PEAK = "Scalecaller Peak"

# 4-man instance dungeons (Horns of the Reach DLC)
DUNGEON_BLOODROOT_FORGE = "Bloodroot Forge"
DUNGEON_FALKREATH_HOLD = "Falkreath Hold"

# 4-man instance dungeons (Imperial City DLC)
DUNGEON_IMPERIAL_PRISON = "Imperial Prison"
DUNGEON_WHITEGOLD_TOWER = "White-Gold Tower"

# 4-man instance dungeons (Shadows of the hist DLC)
DUNGEON_CRADLE_OF_SHADOWS = "Cradle of Shadows"
DUNGEON_RUINS_OF_MAZZATUN = "Ruins of Mazzatun"

# 4-man instance dungeons (Wolfhunter DLC)
DUNGEON_MARCH_OF_SACRIFICES = "March of Sacrifices"
DUNGEON_MOON_HUNTER_KEEP = "Moon Hunter Keep"

# 4-man instance dungeons (Wrathstone DLC)
DUNGEON_FROSTVAULT = "Frostvault"
DUNGEON_DEPTHS_OF_MALATAR = "Depths of Malatar"

# 4-man instance dungeons (Elsweyer DLC)
DUNGEON_ORCREST = "Orcrest"
DUNGEON_RIMMEN_NECROPOLIS = "Rimmen Necropolis"

# 4-man instance dungeons (Scalebreaker DLC)
DUNGEON_MOONGRAVE_FANE = "Moongrave Fane"
DUNGEON_LAIR_OF_MAARSELOK = "Lair of Maarselok"

# full 4-man dungeon list (with all DLC)
LIST_ESO_DUNGEONS = [
    DUNGEON_ARX_CORINIUM,
    DUNGEON_BANISHED_CELLS_I,
    DUNGEON_BANISHED_CELLS_II,
    DUNGEON_BLACKHEART_HAVEN,
    DUNGEON_BLESSED_CRUCIBLE,
    DUNGEON_CITY_OF_ASH_I,
    DUNGEON_CITY_OF_ASH_II,
    DUNGEON_CRYPT_OF_HEARTS_I,
    DUNGEON_CRYPT_OF_HEARTS_II,
    DUNGEON_DARKSHADE_CAVERNS_I,
    DUNGEON_DARKSHADE_CAVERNS_II,
    DUNGEON_DIREFROST_KEEP,
    DUNGEON_FUNGAL_GROTTO_I,
    DUNGEON_FUNGAL_GROTTO_II,
    DUNGEON_ELDEN_HOLLOW_I,
    DUNGEON_ELDEN_HOLLOW_II,
    DUNGEON_SELENES_WEB,
    DUNGEON_SPINDLECLUTCH_I,
    DUNGEON_SPINDLECLUTCH_II,
    DUNGEON_TEMPEST_ISLAND,
    DUNGEON_VAULTS_OF_MADNESS,
    DUNGEON_VOLENFELL,
    DUNGEON_WAYREST_SEWERS_I,
    DUNGEON_WAYREST_SEWERS_II,
    DUNGEON_FENG_LAIR,
    DUNGEON_SCALECALLER_PEAK,
    DUNGEON_BLOODROOT_FORGE,
    DUNGEON_FALKREATH_HOLD,
    DUNGEON_IMPERIAL_PRISON,
    DUNGEON_WHITEGOLD_TOWER,
    DUNGEON_CRADLE_OF_SHADOWS,
    DUNGEON_RUINS_OF_MAZZATUN,
    DUNGEON_MARCH_OF_SACRIFICES,
    DUNGEON_MOON_HUNTER_KEEP,
    DUNGEON_FROSTVAULT,
    DUNGEON_DEPTHS_OF_MALATAR,
    DUNGEON_ORCREST,
    DUNGEON_RIMMEN_NECROPOLIS,
    DUNGEON_MOONGRAVE_FANE,
    DUNGEON_LAIR_OF_MAARSELOK
]

# 16-man Raids/Trials (with all DLC)
RAID_AETHERIAN_ARCHIVE = "Aetherian Archive"
RAID_HEL_RA_CITADEL = "Hel Ra Citadel"
RAID_SANCTUM_OPHIDIA = "Sanctum Ophidia"
RAID_MAW_OF_LORKHAJ = "Maw of Lorkhaj"
RAID_HALLS_OF_FABRICATION = "The Halls of Fabrication"
RAID_ASYLUM_SANCTORIUM = "Asylum Sanctorium"
RAID_CLOUDREST = "Cloudrest"
RAID_SUNSPIRE = "Sunspire"

# full 16-man raid list (with all DLC)
LIST_ESO_RAIDS = [
    RAID_AETHERIAN_ARCHIVE,
    RAID_HEL_RA_CITADEL,
    RAID_SANCTUM_OPHIDIA,
    RAID_MAW_OF_LORKHAJ,
    RAID_HALLS_OF_FABRICATION,
    RAID_ASYLUM_SANCTORIUM,
    RAID_CLOUDREST,
    RAID_SUNSPIRE
]
